import { addDays } from 'date-fns';
import { ReportRequestDto } from '../dto/report-request.dto';
import { ReportResponseDto } from '../dto/report-response.dto';
import { ReportEntity, ReportStatusValues } from '../entities/report.entity';
import { IReportRepository } from '../repositories/report.repository';
import { IAuditService } from './audit.service';
import { generateReportId } from '../utils/id-generator';
import { validateDateRange, isLargeDateRange } from '../utils/date-validator';
import { ReportGenerationError } from '../utils/errors';
import config from '../config';

export interface IReportService {
  generateReport(request: ReportRequestDto): Promise<ReportResponseDto>;
}

export class ReportService implements IReportService {
  constructor(
    private readonly reportRepository: IReportRepository,
    private readonly auditService: IAuditService
  ) {}

  async generateReport(request: ReportRequestDto): Promise<ReportResponseDto> {
    // Validate date range
    validateDateRange(request.dateRange.startDate, request.dateRange.endDate);

    this.auditService.log({
      action: 'report_generation_started',
      status: 'success',
      details: {
        reportType: request.reportType,
        format: request.format,
      },
    });

    try {
      // Check if large date range (requires async processing)
      const isLarge = isLargeDateRange(
        request.dateRange.startDate,
        request.dateRange.endDate
      );

      const reportId = generateReportId();
      const now = new Date();
      const expiresAt = addDays(now, config.report.expiryDays);
      const downloadUrl = `${config.report.downloadBaseUrl}/${reportId}.${request.format}`;

      const reportEntity: ReportEntity = {
        id: '', // Will be generated by database
        reportId,
        reportType: request.reportType,
        startDate: new Date(request.dateRange.startDate),
        endDate: new Date(request.dateRange.endDate),
        format: request.format,
        includeGraphs: request.includeGraphs || false,
        generatedAt: now,
        expiresAt,
        downloadUrl,
        status: isLarge ? ReportStatusValues.PENDING : ReportStatusValues.COMPLETED,
        createdAt: now,
        updatedAt: now,
      };

      // Save report to database
      const savedReport = await this.reportRepository.create(reportEntity);

      // If large date range, queue for async processing
      if (isLarge) {
        this.auditService.log({
          action: 'report_queued_async',
          status: 'success',
          details: {
            reportId: savedReport.reportId,
            reportType: savedReport.reportType,
          },
        });
      }

      this.auditService.log({
        action: 'report_generation_completed',
        status: 'success',
        details: {
          reportId: savedReport.reportId,
          reportType: savedReport.reportType,
        },
      });

      return this.mapToResponseDto(savedReport);
    } catch (error) {
      this.auditService.log({
        action: 'report_generation_failed',
        status: 'failure',
        error: error instanceof Error ? error.message : 'Unknown error',
      });

      throw new ReportGenerationError('Failed to generate report');
    }
  }

  private mapToResponseDto(report: ReportEntity): ReportResponseDto {
    return {
      reportId: report.reportId,
      reportType: report.reportType,
      generatedAt: report.generatedAt.toISOString(),
      downloadUrl: report.downloadUrl,
      expiresAt: report.expiresAt.toISOString(),
    };
  }
}
